### ISSUE TITLE
Faster IN queries when using Postgresql

### ISSUE THREAD

**Issue by cowwoc** [jOOQ/jOOQ#13269]
### Use case:

Running a query with a large (~200k) IN-list.

### Possible solution you'd like to see:

Implement https://dba.stackexchange.com/a/91539/4719.
See also https://stackoverflow.com/a/24647700/14731

### Possible workarounds:

Not sure.

### Versions:

- jOOQ: 3.15.3
- Java: 17
- Database (include vendor): Postgresql 14
- OS: Microsoft Windows [Version 10.0.19044.1586]
- JDBC Driver (include name if inofficial driver): org.postgresql.postgresql

**Comment by cowwoc** [comment]
As a workaround, I tried implementing:

```
SELECT *
FROM mytable
INNER JOIN (
  VALUES (1), (2), (3), (4), (5)
) vals(v)
ON (somevalue = v);
```

but couldn't figure out how to construct `VALUES (1), (2), (3), (4), (5)` using JOOQ. `DSL.values()` constructed `VALUES (1 2, 3, 4, 5)` which isn't what I wanted.

**Comment by lukaseder** [comment]
I'm not sure what you were originally requesting here. It's not jOOQ's job to fix such hard to prove performance issues.

The idea that some vendor X has terrible performance for operation O1 but acceptable performance for a logically equivalent operation O2 is innate to SQL, regrettably. This has been a very popular article at the time I published it, and it produced a few optimisations in PostgreSQL already as it was also discussed on the hackers mailing lists: https://blog.jooq.org/10-cool-sql-optimisations-that-do-not-depend-on-the-cost-model

The one you're observing here would be worthy of publishing to the PG hackers mailing list as well (they're aware of it, but it's always good to remind them of what's troubling users).

But back to jOOQ, jOOQ can't decide for you what is the best equivalent syntax for any syntax you choose to write, because there are dozens of possible alternatives, and the fact whether one is better than the other depends on dozens of factors (storage, memory, indexes, operand sizes, query complexity, etc. etc.), so the probability of jOOQ getting it right is slim.

You, yourself, can use the preferred operator, of course. Use `DSL.values(Row1...)`, or just plain SQL templating. You could also use a `VisitListener` to dynamically replace all your `IN` predicate by a preferred `VALUES` expression.

**Comment by lukaseder** [comment]
(There are already many other issues discussing user-defined SQL transformation capabilities, though)

**Comment by cowwoc** [comment]
@lukaseder Maybe I missed something, but it's still not clear to me how to represent `VALUES (1), (2), (3), (4), (5)` in JOOQ. As mentioned above, invoking `DSL.values(1, 2, 3, 4, 5)` results in `VALUES (1, 2, 3, 4, 5)` which is not equivalent to the aforementioned syntax.

**Comment by cowwoc** [comment]
Okay, I see what you're saying now.

I was invoking `DSL.values(DSL.row(indices))` whereas you're saying I should invoke `DSL.values(DSL.row(indices[0]), DSL.row(indices[1], ...)`

I think I was thrown off by the fact that `DSL.values()` has overloads with up to 22 arguments, and beyond that I had to pass in a primitive array. `indices` is a `List<Integer>` so it goes without saying that I could have converted it to a primitive array but it didn't immediately jump out at me. I saw that `DSL.row()` accepted a collection so I jumped on that.

Is it possible to add ` DSL.values(Collection<Row>)` overload to make this more intuitive?

**Comment by lukaseder** [comment]
> I think I was thrown off by the fact that `DSL.values()` has overloads with up to 22 arguments, and beyond that I had to pass in a primitive array.

While you like to create:

```sql
VALUES (1), (2), (3)
```

You might as well have created

```sql
VALUES (1, 'a'), (2, 'b'), (3, 'c')
```

Note that while it may be tempting to offer a `values(T...)` overload "for convenience", that would be a terrible idea: https://github.com/jOOQ/jOOQ/issues/11798

> I saw that `DSL.row()` accepted a collection so I jumped on that.

Yeah, we support more than 22-arity tuples, but without the type safety

> Is it possible to add ` DSL.values(Collection<Row>)` overload to make this more intuitive?

See https://github.com/jOOQ/jOOQ/issues/7098

**Comment by cowwoc** [comment]
Sounds good. Thank you for answering my questions.
