### ISSUE TITLE
Using DSLContext.transactionResult with setLocal

### ISSUE THREAD

**Issue by ozlmulg** [jOOQ/jOOQ#14778]
### Your question

I am trying to set a local variable on Postgresql by using reactive way inside dslContext.transactionResult. 
I want to keep the user_id, the id of the user who changed the product table, in the product history table with the help of trigger.

My trigger function for product history table uses this script inside it to fetch user_id variable.

```
DECLARE user_id text := current_setting('user_id', true);
```

Actually i want to create the same behaviour of this sql script by using jooq reactive transaction support.

```
BEGIN;
SET LOCAL user_id = 'XXXXXXXXX';
insert into .....
COMMIT;
```

But the following jooq code does not works, the user_id variable does not take the value of it in product history table.

```
  public Mono<Product> upsertProduct(Long productId, String name, String userId) {
    return dslContext.transactionResult(configuration -> {
      DSLContext ctx = DSL.using(configuration);
      return Mono.from(ctx.setLocal(DSL.name("user_id"), DSL.value(userId)))
                 .flatMap(result -> Mono.from(ctx.insertInto(PRODUCT)
                                                 .set(PRODUCT.ID, productId)
                                                 .set(PRODUCT.NAME, name)
                                                 .onConflictOnConstraint(Keys.PRODUCT_PK)
                                                 .doUpdate()
                                                 .set(PRODUCT.NAME, name)
                                                 .returning())
                                        .map(dbRecord -> dbRecord.into(Product.class)));
    });
  }
```

Please could you help me about whether the reactive of setLocal is been supporting or not? Because when i try to use non-reactive way by using dslContext.transaction.. it works and i can see the local variable on product history table.

### jOOQ Version

3.16.5

### Database product and version

PostgreSQL 11.18 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit

### Java Version

17

### OS Version

macOS Big Sur [Version 11.6]

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.3.6

**Comment by lukaseder** [comment]
Thanks for your message. While the procedural language extensions are a jOOQ Professional Edition feature, we do support the anonymous block statement on all dialects and in all editions, so you could just use that, instead: https://www.jooq.org/doc/latest/manual/sql-building/procedural-statements/procedural-block/

Regarding R2DBC support, a lot of bugs have been fixed recently. Can you please upgrade and try again.

**Comment by ozlmulg** [comment]
I have upgraded Jooq to 3.18.0 version, 

the current `dslContext.transactionResult` still does not set local variable, 
and i also tried the new `dslContext.transactionPublisher` method, but it does not commit the scripts to database.
`dslContext.begin` that you mentioned works but it does not return the updated record so we will need to select the record again after each update operation.

Actually i want to understand why transaction does not work, i will create a sample project to reproduce the problem, and send in this issue. @lukaseder

**Comment by lukaseder** [comment]
Thanks for the feedback. Might as well be a bug, then. I overlooked your `returning()` call. Yes of course, in that case, you can't use `BEGIN` in PostgreSQL.

**Comment by ozlmulg** [comment]
Hi @lukaseder 

I created a [sample project](https://github.com/ozlmulg/sample-project) for you.
Please could you take a look when you have time?

Thank you.

**Comment by lukaseder** [comment]
Thanks for the sample project. I'm on windows so I won't be able to use `make` easily. We have a template for fully self contained reproducers here, which might be useful next time: https://github.com/jOOQ/jOOQ-mcve

In any case, I'll try to convert your sample to something that runs on my machine and will provide feedback, soon.

**Comment by lukaseder** [comment]
So, I can reproduce this:

```
http://localhost:8080/products/jdbc/upsert/2?name=x&userId=1
```

Produces something like:

> {"id":2,"name":"x","createdAt":[2023,5,6,2,54,5,306132000],"updatedAt":[2023,5,6,15,54,24,220990000],"version":4,"changelogId":"731c05c3-8c45-491a-bdbb-fa97b462444f"}

Whereas:

```
http://localhost:8080/products/r2dbc/upsert/2?name=x&userId=1
```

Produces:

> {"message":"Not Found","_links":{"self":{"href":"/products/r2dbc/upsert/2?name=x&userId=1","templated":false}},"_embedded":{"errors":[{"message":"Page Not Found"}]}}

**Comment by lukaseder** [comment]
This simple test doesn't reproduce the problem:

```java
println(
    Flux.from(ctx.transactionPublisher(c -> {
        return Mono.from(c.dsl().setLocal("user.id", val("y")))
            .flatMap(r -> Mono.from(c.dsl().selectOne()));
    })).blockFirst()
);
```

**Comment by ozlmulg** [comment]
You can check product_changelog table to check whether the code can successfully set a local variable or not within transaction when upserting a product.

**Comment by ozlmulg** [comment]
I tried jdbc with dslContext.transactionPublisher, it works but the others (upsertWithJdbc , upsertWithR2dbc) dont work.
Actually i can continue with jdbc and dslContext.transactionPublisher for now. But i want to use r2dbc , so i really want to solve the problem about `upsertWithR2dbc`

**success:**
dslContext.transactionPublisher -> works with jdbc for setLocal

**fails:**
dslContext.transactionResult -> does not work with jdbc for setLocal
dslContext.transactionPublisher -> does not work with r2dbc for setLocal

**Comment by lukaseder** [comment]
This also produces `null`:

```java
System.out.println(Mono.from(cf.create())
    .flatMap(c -> Mono.from(c.createStatement("drop table if exists t").execute())
        .flatMap(r -> Mono.from(r.getRowsUpdated())))
    .block()
);
```

I think there has been a fundamental misunderstanding about R2DBC's `Result::getRowsUpdated`. Its Javadoc reads:

> Returns the number of rows updated by a query against a database. May be empty if the query did not update any rows. 

So, unlike JDBC, which always returns a value, e.g. `0`, this method returns nothing when a statement doesn't produce an update count.

When we use R2DBC directly with a transaction like this:

```java
System.out.println(
    Flux.from(cf.create())
        .flatMap(c ->
            Flux.from(c.beginTransaction())
                .thenMany(
                    Flux.from(c.createStatement("set local \"user.id\" = 'y'").execute()).flatMap(r ->
                        Flux.from(r.getRowsUpdated()).map(l -> println(l))
                    )
                )
                .flatMap(i -> { println(i); return Flux.from(c.commitTransaction()).thenMany(Mono.just(i)); })
        )
        .collectList()
        .block()
    );
```

Then, the result is also empty: `[]`

But the transaction is never committed!

```
14:39:35,079 DEBUG [QUERY                         ] - [cid: 0x1][pid: 433] Executing query: BEGIN
14:39:35,079 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 433] Request:  Query{query='BEGIN'}
14:39:35,086 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 433] Response: CommandComplete{command=BEGIN, rowId=null, rows=null}
14:39:35,086 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 433] Response: ReadyForQuery{transactionStatus=TRANSACTION}
14:39:35,086 DEBUG [LoggingStatement              ] - Statement::execute       
14:39:35,086 DEBUG [QUERY                         ] - [cid: 0x1][pid: 433] Executing query: set local "user.id" = 'y'
14:39:35,086 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 433] Request:  Query{query='set local "user.id" = 'y''}
14:39:35,089 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 433] Response: CommandComplete{command=SET, rowId=null, rows=null}
14:39:35,090 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 433] Response: ReadyForQuery{transactionStatus=TRANSACTION}
[]
```

This is because the empty update count publisher never produces an entry in the subsequent `flatMap()` that completes the transaction. The same is the case in your case. You have to use a different operator:

```java
println(
    Flux.from(ctx.transactionPublisher(c -> {
        return Flux.from(c.dsl().setLocal("user.id", DSL.val("y")))
            .thenMany(Flux.from(c.dsl().selectOne()));
    })).blockFirst()
);
```

This now works and prints:

```
+----+
| one|
+----+
|   1|
+----+
```

Try it here:

```java
  public Mono<Product> upsertWithR2dbc(long id, String name, Optional<String> userId) {
    return Mono.from(dslContextR2dbc.transactionPublisher(configuration -> {
      DSLContext ctx = DSL.using(configuration);
      return setLocalUserId(ctx, userId)
          .thenMany(getInsertReturning(ctx, id, name));
    }));
  }
```

Now the service works correctly. So, there's no bug in jOOQ. This is just how R2DBC, and by consequence, jOOQ works. Very subtle. We might argue that perhaps there's a difference between the JDBC backed approach and the R2DBC backed one, given that the `flatMap()` version works when backed by JDBC (which returns an update count of `0`). I'm going to report that to R2DBC.

Perhaps for better visibility for other jOOQ users, would you have some time to ask the question again on Stack Overflow? I could copy my answer there, so people will find the solution more quickly:
https://stackoverflow.com/questions/tagged/jooq

This is quite the

**Comment by lukaseder** [comment]
After giving this some additional thought, I don't think it's an R2DBC design problem. While JDBC returns `0` when executing a single query, that's possible because the return type of that `Statement::executeUpdate` method is `int`. But when running JDBC in a streaming fashion (see this fun article: https://blog.jooq.org/how-i-incorrectly-fetched-jdbc-resultsets-again/), then any interleaved statement that doesn't produce an update count will not produce any result token at all. So, quite possibly, it's not possible for a streaming driver (like an R2DBC driver) to even send any signal at all.

**Comment by ozlmulg** [comment]
Okay, i got it, thank you so much, i tried to use `then` instead of `map`, and it works now 🥇
Sure, I can post on stackoverflow also 👍 

So the last status is this:

**success:**
dslContext.transactionPublisher & jdbc -> works for setLocal
dslContext.transactionPublisher & r2dbc -> does not work for setLocal

**fails:**
dslContext.transactionResult & jdbc -> does not work for setLocal

I am writing because maybe someone use `dslContext.transactionResult` & jdbc for setLocal
But we can use `transactionPublisher` instead of `transactionResult` here

```
  public Mono<Product> upsertWithJdbc(long id, String name, Optional<String> userId) {
    return dslContextJdbc.transactionResult(configuration -> {
      DSLContext ctx = DSL.using(configuration);
      return setLocalUserId(ctx, userId)
          .flatMap(result -> getInsertReturning(ctx, id, name));
    });
  }
```

so this code should be like this if you use jdbc:

```
  public Mono<Product> upsertWithJdbc(long id, String name, Optional<String> userId) {
    return Mono.from(dslContextJdbc.transactionPublisher(configuration -> {
      DSLContext ctx = DSL.using(configuration);
      return setLocalUserId(ctx, userId)
          .flatMap(result -> getInsertReturning(ctx, id, name));
    }));
  }
```

Thank you again for your time 👍

**Comment by lukaseder** [comment]
Wonderful, thank you!

**Comment by ozlmulg** [comment]
@lukaseder 

When i upgraded jooq version to 3.18.0 it started to log this warns, our postgresql version is 11.8:
What the meaning of this? I have tested the new jooq version and it works with 11.8 but it still gives this warning.
Do you think it can cause a problem with this version? 

```
Version mismatch         : Database version is older than what dialect POSTGRES supports: 11.18. Consider https://www.jooq.org/download/support-matrix to see what jOOQ version and edition supports which RDBMS versions.
```

**Comment by lukaseder** [comment]
This log message was added to various versions recently with #11355. It helps users recognise the risk of using an unsupported combination of:

- jOOQ version
- SQL dialect version (available in commercial distributions)
- Server version

We don't support your combination and recommend you either downgrade jOOQ, upgrade your PostgreSQL version, or upgrade to a commercial jOOQ distribution that still supports PG 11. You'll find the support matrix in the link from the log message.
