### ISSUE TITLE
[BUG] ClassNotFoundException in Custom Code Generator Strategy

### ISSUE THREAD

**Issue by shilohooo** [jOOQ/jOOQ#19481]
### Expected behavior

JOOQ should successfully generate the required code after compilation

### Actual behavior

When generating code with a custom code generator strategy, the following error occurs:

```java
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jooq:jooq-codegen-maven:3.20.10:generate (generate-jooq) on project jooq-pgsql-example: Error running jOOQ code generation tool
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error running jOOQ code generation tool
    at org.jooq.codegen.maven.Plugin.execute (Plugin.java:246)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
Caused by: java.lang.ClassNotFoundException: com.github.shiloh.jooq.codegen.CustomJooqCodeGenerator
    at java.net.URLClassLoader.findClass (URLClassLoader.java:445)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:593)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:526)
    at org.jooq.tools.ClassUtils.loadClass (ClassUtils.java:58)
    at org.jooq.codegen.GenerationTool.loadClass (GenerationTool.java:1289)
    at org.jooq.codegen.GenerationTool.run0 (GenerationTool.java:415)
    at org.jooq.codegen.GenerationTool.run (GenerationTool.java:254)
    at org.jooq.codegen.GenerationTool.generate (GenerationTool.java:249)
    at org.jooq.codegen.maven.Plugin.execute (Plugin.java:243)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
```

### Steps to reproduce the problem

[Here](https://github.com/shilohooo/jooq-pgsql-bug-reproduce) is a minimal reproduce sample

1. Clone the repository above.
2. Open the project in your IDE (like IntelliJ IDEA).
3. Install all dependencies.
4. Run following command: 

```shell
mvn clean compile -X
```

#### Code generation config

```xml
<plugin>
    <groupId>org.jooq</groupId>
    <artifactId>jooq-codegen-maven</artifactId>
    <version>${jooq.version}</version>
    <executions>
        <execution>
            <id>generate-jooq</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>generate</goal>
            </goals>
        </execution>
    </executions>

    <configuration>
        <jdbc>
            <driver>org.postgresql.Driver</driver>
            <url>jdbc:postgresql://127.0.0.1:15432/jooq_db</url>
            <user>root</user>
            <password>123456</password>
        </jdbc>
        <generator>
            <name>com.github.shiloh.jooq.codegen.CustomJooqCodeGenerator</name>
            <strategy>
                <name>com.github.shiloh.jooq.codegen.CustomJooqCodeGeneratorStrategy</name>
            </strategy>
            <database>
                <name>org.jooq.meta.postgres.PostgresDatabase</name>
                <inputSchema>public</inputSchema>
                <includes>.*</includes>
                <excludes/>
            </database>
            <target>
                <packageName>com.github.shiloh.jooq</packageName>
                <directory>${project.build.directory}/generated-sources</directory>
                <encoding>UTF-8</encoding>
            </target>
            <generate>
                <pojos>true</pojos>
                <daos>true</daos>
            </generate>
        </generator>
    </configuration>
</plugin>
```

#### Custom Generator

```java
public class CustomJooqCodeGenerator extends JavaGenerator {
}
```

```java
public class CustomJooqCodeGeneratorStrategy extends DefaultGeneratorStrategy {
    @Override
    public String getJavaClassExtends(Definition definition, Mode mode) {
        log.info("com.github.shiloh.jooq.codegen.CustomJooqGenerator.getJavaClassExtends: {}, {}", definition, mode);
        if (definition instanceof TableDefinition && Mode.DAO.equals(mode)) {
            return BaseDaoImpl.class.getName();
        }

        return super.getJavaClassExtends(definition, mode);
    }

    @Override
    public String getJavaClassName(Definition definition, Mode mode) {
        final String javaClassName = super.getJavaClassName(definition, mode);
        log.info("com.github.shiloh.jooq.codegen.CustomJooqGenerator.getJavaClassName: {}, {}, {}", definition.getClass().getName(), mode, javaClassName);
        final String javaClassNameWithoutPrefix = javaClassName.replace("T", "");
        return switch (mode) {
            case DEFAULT -> String.format("%sTable", javaClassNameWithoutPrefix);
            case POJO -> String.format("%sPojo", javaClassNameWithoutPrefix);
            default -> javaClassNameWithoutPrefix;
        };
    }
}
```

### jOOQ Version

Open Source Edition v3.20.10

### Database product and version

PostgreSQL 18.1 (Debian 18.1-1.pgdg13+2) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit

### Java Version

OpenJDK 21.0.9

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.8

**Comment by lukaseder** [comment]
Thanks for your report. Your reproducer is not accessible (404 error).

In any case, you cannot expect jOOQ to find stuff on your classpath which isn't on your classpath. There are various solutions to this problem, including:

- Creating a maven module for your strategy and putting that module on the classpath of the code generation module
- Using the inline `<java>` element to embed the strategy source code in the code generation configuratino, for in-memory compilation

All of this is documented throughout the manual, including:

- https://www.jooq.org/doc/latest/manual/code-generation/codegen-object-naming/codegen-generatorstrategy
- https://www.jooq.org/doc/latest/manual/code-generation/codegen-dependencies

**Comment by shilohooo** [comment]
Sorry for the private repo, I've set it as a [public repo](https://github.com/shilohooo/jooq-pgsql-bug-reproduce)

I've tried the first one solution, it works.

But when i change the source code of my custom strategy, i need to run `mvn clean install` first, then run `mvn clean compile`, otherwise, the codegen plugin will not apply the new strategy:(

sub module pom file here:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.github.shiloh</groupId>
    <artifactId>jooq-postgresql-demo</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>jooq-postgresql-demo-codegen</artifactId>

  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jooq</groupId>
        <artifactId>jooq-codegen-maven</artifactId>
        <version>${jooq.version}</version>
        <dependencies>
          <dependency>
            <groupId>com.github.shiloh</groupId>
            <artifactId>jooq-postgresql-demo-codegen</artifactId>
            <version>${project.version}</version>
          </dependency>
        </dependencies>

        <executions>
          <execution>
            <id>generate-jooq</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>

        <configuration>
          <jdbc>
            <driver>org.postgresql.Driver</driver>
            <url>jdbc:postgresql://127.0.0.1:15432/jooq_db</url>
            <user>root</user>
            <password>123456</password>
          </jdbc>
          <generator>
            <name>com.github.shiloh.jooq.codegen.CustomJooqCodeGenerator</name>
            <strategy>
              <name>com.github.shiloh.jooq.codegen.CustomJooqCodeGeneratorStrategy</name>
            </strategy>
            <database>
              <name>org.jooq.meta.postgres.PostgresDatabase</name>
              <inputSchema>public</inputSchema>
              <includes>.*</includes>
              <excludes/>
            </database>
            <target>
              <packageName>com.github.shiloh.jooq</packageName>
              <directory>${project.build.directory}/generated-sources</directory>
              <encoding>UTF-8</encoding>
            </target>
            <generate>
              <pojos>true</pojos>
              <interfaces>true</interfaces>
              <daos>true</daos>
            </generate>
          </generator>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

**Comment by lukaseder** [comment]
> But when i change the source code of my custom strategy, i need to run `mvn clean install` first, then run `mvn clean compile`, otherwise, the codegen plugin will not apply the new strategy:(

I don't know what else to say, sorry. This is how Maven works. If you don't want to use jOOQ's in-memory compilation support, you'll have to extract the custom strategy into a separate module. Maven is very good at managing multi-module projects. I don't know why folks always want to work with single-module projects, even if things obviously cannot work this way, because of the way Maven is designed and how dependencies are resolved.

**Comment by shilohooo** [comment]
Yes, if a submodule wants to use the latest code, it must be reinstalled, and Maven is designed that way.

I just tried to use in memory compilation, but still encountered an error (I want to specify a base class for the generated DAO class)

Here is my JOOQ codegen plugin config:

```xml
<plugins>
    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven-compiler-plugin.version}</version>
        <configuration>
            <encoding>utf-8</encoding>
            <source>${maven.compiler.source}</source>
            <target>${maven.compiler.target}</target>
            <compilerArgs>
                <arg>-parameters</arg>
            </compilerArgs>
            <fork>true</fork>
        </configuration>
    </plugin>

    <plugin>
        <groupId>org.jooq</groupId>
        <artifactId>jooq-codegen-maven</artifactId>
        <version>${jooq.version}</version>
        <executions>
            <execution>
                <id>generate-jooq</id>
                <phase>generate-sources</phase>
                <goals>
                    <goal>generate</goal>
                </goals>
            </execution>
        </executions>

        <configuration>
            <jdbc>
                <driver>org.postgresql.Driver</driver>
                <url>jdbc:postgresql://127.0.0.1:15432/jooq_db</url>
                <user>root</user>
                <password>123456</password>
            </jdbc>
            <generator>
                <strategy>
                    <name>com.github.shiloh.jooq.codegen.CustomJooqCodeGeneratorStrategy</name>
                    <java>
                        package com.github.shiloh.jooq.codegen;

                        import com.github.shiloh.base.dao.impl.BaseDaoImpl;
                        import lombok.extern.slf4j.Slf4j;
                        import org.jooq.codegen.DefaultGeneratorStrategy;
                        import org.jooq.meta.Definition;
                        import org.jooq.meta.TableDefinition;

                        /**
                        * 自定义 JOOQ 代码生成策略
                        *
                        * @author shiloh
                        */
                        @Slf4j
                        public class CustomJooqCodeGeneratorStrategy extends DefaultGeneratorStrategy {
                            @Override
                            public String getJavaClassExtends(Definition definition, Mode mode) {
                                log.info("com.github.shiloh.jooq.codegen.CustomJooqGenerator.getJavaClassExtends: {}, {}", definition, mode);
                                if (definition instanceof TableDefinition &amp;&amp; Mode.DAO.equals(mode)) {
                                return BaseDaoImpl.class.getName();
                                }

                                return super.getJavaClassExtends(definition, mode);
                            }

                            @Override
                            public String getJavaClassName(Definition definition, Mode mode) {
                                final String javaClassName = super.getJavaClassName(definition, mode);
                                log.info("com.github.shiloh.jooq.codegen.CustomJooqGenerator.getJavaClassName: {}, {}, {}", definition.getClass().getName(), mode, javaClassName);
                                final String javaClassNameWithoutPrefix = javaClassName.replace("T", "");
                                return switch (mode) {
                                case DEFAULT -> String.format("%sTable", javaClassNameWithoutPrefix);
                                case POJO -> String.format("%sPojo", javaClassNameWithoutPrefix);
                                default -> javaClassNameWithoutPrefix;
                                };
                            }
                        }
                    </java>
                </strategy>
                <database>
                    <name>org.jooq.meta.postgres.PostgresDatabase</name>
                    <inputSchema>public</inputSchema>
                    <includes>.*</includes>
                    <excludes/>
                </database>
                <target>
                    <packageName>com.github.shiloh.jooq</packageName>
                    <directory>${project.build.directory}/generated-sources</directory>
                    <encoding>UTF-8</encoding>
                </target>
                <generate>
                    <!--              生成和表一一对应的 Pojo-->
                    <pojos>true</pojos>
                    <interfaces>true</interfaces>
                    <daos>true</daos>
                </generate>
            </generator>
        </configuration>
    </plugin>
</plugins>
```

and the error log:

```java
[ERROR] /com/github/shiloh/jooq/codegen/CustomJooqCodeGeneratorStrategy.java:3: 错误: 程序包com.github.shiloh.base.dao.impl不存在
[ERROR]                                 import com.github.shiloh.base.dao.impl.BaseDaoImpl;
[ERROR]                                                                       ^
[ERROR] 1 个错误
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jooq:jooq-codegen-maven:3.20.10:generate (generate-jooq) on project jooq-pgsql-example: Error running jOOQ code generation tool                                                                                                                                                                      
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error running jOOQ code generation tool
    at org.jooq.codegen.maven.Plugin.execute (Plugin.java:246)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
Caused by: org.jooq.tools.reflect.ReflectException: Compilation error: 注: 由于在类路径中发现了一个或多个处理程序，因此启用了
  批注处理。未来发行版的 javac 可能会禁用批注处理，                                                                                                                                         
  除非至少按名称指定了一个处理程序 (-processor)，                                                                                                                                           
  或指定了搜索路径 (--processor-path, --processor-module-path)，                                                                                                                            
  或显式启用了批注处理 (-proc:only, -proc:full)。                                                                                                                                           
  可使用 -Xlint:-options 隐藏此消息。                                                                                                                                                       
  可使用 -proc:none 禁用批注处理。                                                                                                                                                          
/com/github/shiloh/jooq/codegen/CustomJooqCodeGeneratorStrategy.java:3: 错误: 程序包com.github.shiloh.base.dao.impl不存在                                                                   
                                import com.github.shiloh.base.dao.impl.BaseDaoImpl;                                                                                                         
                                                                      ^                                                                                                                     
1 个错误                                                                                                                                                                                    
                                                                                                                                                                                            
    at org.jooq.tools.reflect.Compile.compile (Compile.java:118)
    at org.jooq.tools.reflect.Compile.compile (Compile.java:57)
    at org.jooq.tools.reflect.Reflect.compile (Reflect.java:107)
    at org.jooq.codegen.GenerationTool.compile (GenerationTool.java:1096)
    at org.jooq.codegen.GenerationTool.run0 (GenerationTool.java:440)
    at org.jooq.codegen.GenerationTool.run (GenerationTool.java:254)
    at org.jooq.codegen.GenerationTool.generate (GenerationTool.java:249)
    at org.jooq.codegen.maven.Plugin.execute (Plugin.java:243)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

It seems that the class [com.github.shiloh.base.dao.impl.BaseDaoImpl] cannot be found:(

**Comment by lukaseder** [comment]
I think this is self-explanatory? If you want to use in-memory compilation, you will still have to provide all the dependencies to the code generator.

In the specific case of `com.github.shiloh.base.dao.impl.BaseDaoImpl`, why do you import it to call `BaseDaoImpl.class.getName()`, when you could just return `"com.github.shiloh.base.dao.impl.BaseDaoImpl"`

**Comment by shilohooo** [comment]
Thanks for you solution! It works for me:)
