### ISSUE TITLE
Batch statements do not work when queries contain inlined bind variables

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3940]
The synthetic `USING DUAL` clause that can be passed to a `MERGE` statement emits a bind value on calls to `Query.getParams()`. This parameter is extracted by batch statements, which then expect an actual bind value for the statement.

Obviously, this is very intransparent from a user perspective, as users would not expect any bind values to be there from this `USING DUAL` clause.

Fixing this is delicate as users may have implemented workarounds to get this to work. It will not be a good idea to merge a potential fix to 3.3, 3.4, and 3.5 versions as this fix will constitute an incompatible change of behaviour - which is acceptable only in minor releases.

----
See also:
https://groups.google.com/forum/#!topic/jooq-user/0ChrfCfomYA

**Comment by steveash** [comment]
I just upgraded to jooq 3.5.2 from 3.3.1 and somewhere between this behavior changed.  I am now NOT having to set the "1" for the dual as a bind parameter.  When I upgraded all of sudden all of my MERGE queries with bind values failed with a sql server error:
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The index 17 is out of range.

Removing the literal '1' I had at the front of the values fixed it.  So maybe this is fixed?

**Comment by lukaseder** [comment]
Hmm, no the issue hasn't been fixed yet. We have this integration test here, which still fails:

```java
BatchBindStep batch = create().batch(
    mergeInto(TBook())
    .usingDual()
    .on(TBook_ID().eq((Integer) null))
    .whenMatchedThenUpdate()
    .set(TBook_TITLE(), (String) null)
);

for (int i = 1; i < 5; i++)
    batch.bind(i, "abc");

assertEquals(4, batch.execute().length);
assertEquals(nCopies(4, "abc"), create().select(TBook_TITLE()).from(TBook()).fetch(TBook_TITLE()));
```

It fails because the `"abc"` bind value is coerced to the type of the `TBook_ID` type

**Comment by steveash** [comment]
Eek! Actually I think we're broken now.  The parameter types in BatchSingle is still length 17 but the batch values only 16 -- and the parameter types have the Integer for the Select 1 in the first spot -- bumping all of the others down causing all kinds of havoc.  So there's some bug in the mssql MERGE sql rendering that has changed since 3.3.1 that is causing one fewer ? to be emitted causing the "index 17 is out of range".

Also when you redo some of this bind stuff, it would be nice to fail earlier and with more useful messages whenever the bind parameters don't match the parameters it expects.

**Comment by steveash** [comment]
Here's the renendered sql with only 16 ?'s instead of 17 (which is what I'm passing to the step.bind()).  Note that I literally just changed the version in the POM.  All of this has been working for months in 3.3.1.  The [one] business with the select 1 seems new.  I don't recall seeing that before...
```
  merge into FRD_SERIAL_BUCKETS using (select 1 [one]) as dummy_82901439([one]) on (account_id = ? and account_bucket_seq = ?) 
  when matched then update set num_items = ?, slope = ?, std_dev = ?, y_intercept = ?, grace_period_offset = ?, 
  average_checks_per_day = ? when not matched then insert 
  (account_id, account_bucket_seq, num_items, slope, std_dev, 
  y_intercept, grace_period_offset, average_checks_per_day) 
  values (?, ?, ?, ?, ?, ?, ?, ?);
```

**Comment by steveash** [comment]
Ok I figured something out.  Let me make sure I'm giving you a complete picture of what I'm doing.
Using merge statements like:
```java
create.batch(create.mergeInto(T)
   .usingDual()
   .on(COL_A.eq((Long) null))
   .whenNot()...
```
Then when I want to bind actual values I call:
```java
step.bind(1, colALongValue, ...)
```
And eventually execute the batch.  In 3.3.1 I had to put that 1 in the bind() args otherwise it would blow up.  At the time I told myself that the '1' was for the SELECT 1 emitted from the usingDual().  
Now in 3.5.2 if I use usingDual() then under the covers that calls DSL.one() which creates a Param with setInline(true).  This seems to supress the parameter from the rendered output -- but it looks like its still getting counted/added to the paramTypes that are being maintained, which explains why I got the mismatched paramTypes and batchValues causing the havoc with truncations when I tried to execute this.  

A workaround for now thats working is:
```java
create.batch(create.mergeInto(T)
   .using(create.select(DSL.val(1, Integer.class)))
   .on(COL_A.eq((Long) null))
   .whenNot()...
```
This creates the SELECT 1 _without_ inlining it so it still get's rendered.
So definitely a bug -- but looks like when this is fixed then this issue (3940) will be fixed too!

**Comment by lukaseder** [comment]
Thank you very much for your detailed analysis!

> Also when you redo some of this bind stuff, it would be nice to fail earlier and with more useful messages whenever the bind parameters don't match the parameters it expects

I agree this would have been useful for debugging, in this case. On the other hand, it's not really a user error...

> So definitely a bug -- but looks like when this is fixed then this issue (3940) will be fixed too!

Yes, it's definitely a bug.

**Comment by lukaseder** [comment]
I originally thought that the issue is related to the `MERGE` statement implementation and that this implementation would need to be changed incompatibly. But the issue is really "just" a general batch statement issue, which can be solved backwards-compatibly, and thus the fix can be merged to older releases.

Merge tickets are:

- #4072 (3.5.3)
- #4073 (3.4.5)
- #4074 (3.3.5)

**Comment by lukaseder** [comment]
@steveash : I understand that this issue has been bothering you for a while now. I can release 3.5.3 (and the other patch releases) on Monday, February 23. Is that timeline OK with you?

**Comment by steveash** [comment]
That would be great!

**Comment by lukaseder** [comment]
OK, let's aim for Monday then.

I've been fixing a couple of additional issues related to bind value extraction, and possibly using them in batch statements... It'll make sense to merge them all to 3.5.3. I will keep you posted.

**Comment by lukaseder** [comment]
@steveash jOOQ 3.5.3 is now available from http://www.jooq.org/download/versions. The public announcement will follow later during the day. The release notes are here: http://www.jooq.org/notes?version=3.5

Let me know if I can be of any further assistance...
